# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

# Use custom format
format = """\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$package\
$docker_context\
$bun\
$nodejs\
$python\
$java\
$cmd_duration $time $jobs\
$line_break\
$character\
"""

# palette = 'catppuccin_macchiato'

[line_break]
disabled = false

[os]
disabled = false
format = "on [($name )]($style)"
style = "bold blue"

[username]
show_always = true

[directory]
# style = "bg:blue fg:crust"
format = "[$path ]($style)"
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "…/"

[docker_context]
format = "[🐳 $context ](blue bold)"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]

[nodejs]
format = "[$symbol($version )]($style)"
detect_files = [ "package.json", ".node-version", ".nvmrc", "!bunfig.toml", "!bun.lock", "!bun.lockb" ]

[bun]
format = 'via [🥟 $version](bold green) '
detect_files = [ "bun.lock", "bun.lockb", "bunfig.toml" ]


[python]
symbol = '🐍 '
format = ' [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = false
python_binary = ['./venv/bin/python', 'python', 'python3', 'python2']

[java]
symbol = " "
format = "via [$symbol($version )]($style)"
 

[fill]
symbol = " "
disabled = false

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](bold green)"

[package]
symbol = "📦 "
format="[$symbol($version )]($style)"
display_private = true
# disabled = true

[jobs]
symbol = "⚙️"
style = "bold red"
number_threshold = 4
symbol_threshold = 1
format = "[$symbol]($style)"

[git_branch]
symbol = "on  "
format = "[$symbol$branch]($style) "
style = "bold purple"


[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
cherry_pick = '[🍒 PICKING](bold red)'
style = "bright-black"

[git_metrics]
disabled = false
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[cmd_duration]
format = "[\\[$duration\\]]($style)"
style = "yellow"

[memory_usage]
symbol = " "

[rust]
symbol = " "


[time]
disabled = false
style = "bold yellow"
format = "[\\[$time\\] ]($style)"

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
